blank_issues_enabled: false
contact_links:
  - name: Repository Community Support
    url: https://github.com/JackEAllen/DraftOnChangeRequested/discussions/categories/q-a
    about: Please ask and answer questions here or contact the repository admin
  - name: Ideas and Features
    url: https://github.com/JackEAllen/DraftOnChangeRequested/discussions/categories/ideas
    about: If you have ideas or suggestions, please first ask them here or contact the admin.
  - name: Security Bugs
    url: https://github.com/JackEAllen/DraftOnChangeRequested/security
    about: We kindly ask that you report any security vulnerabilities to the repository admin to resolve.